name       : delve
version    : 1.4.1
release    : 3
source     :
    - https://github.com/go-delve/delve/archive/v1.4.1.tar.gz : 6d9da41a18905c9819e33f475bf911facba1297674d2312ab5d7e2488fac685a
license    : MIT
homepage   : https://github.com/go-delve/delve/
component  : programming.tools
summary    : Delve is a debugger for the Go programming language
description: |
    Delve is a source level debugger for Go programs.

    Delve enables you to interact with your program by controlling the execution of the process, evaluating variables, and providing information of thread / goroutine state, CPU register state and more.

    The goal of this tool is to provide a simple yet powerful interface for debugging Go programs.
extract    : no
networking : yes
builddeps  :
    - golang
rundeps    :
    - golang
setup      : |
    mkdir -p github.com/go-delve/delve
    tar xf $sources/v${version}.tar.gz -C github.com/go-delve/delve --strip-components 1
    ln -s $workdir src
build      : |
    pushd github.com/go-delve/delve/cmd/dlv
    export GOPATH=$workdir
    go build -p %YJOBS% -o delvebin
install    : |
    install -Dm00755 github.com/go-delve/delve/cmd/dlv/delvebin $installdir/usr/bin/dlv
